### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by tsigouris007** [yuzutech/annotations-action#42]
Continuously stumbling on a generic error:
```
Run yuzutech/annotations-action@v0.1.0
  with:
    repo-token: ***
    input: ./annotations.json
Error: Not Found
```
The `annotations.json` file is there and statically defined to test this as:
```
    {
      "file": "temp3.jsx",
      "start_line": 5,
      "end_line": 10,
      "title": "title for my annotation",
      "message": "my message",
      "annotation_level": "failure"
    }
]  
```
The `temp3.jsx` file is also there.
But `Error: Not Found` keeps on giving.
My action is:
```
name: Annotations
on:
  pull_request:
    paths:
      - '*.js'
      - '*.jsx'
jobs:
  Annotations:
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Annotate
        if: github.event_name == 'pull_request'
        uses: yuzutech/annotations-action@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          input: ./annotations.json
```
I also tried with `input: annotations.json` and `input: $(pwd)/annotations.json` but same error.
Am I doing something wrong?
