### ISSUE TITLE
Can annotations be shown to PRs on each commit on code?

### ISSUE THREAD

**Issue by tsigouris007** [yuzutech/annotations-action#43]
My scenario is that I have integrated a static code analysis tool that produces a json file in the format needed for this action to work.
Sample of my action:
```
      - name: Beautify + create annotations result
        run: |
          ruby parser.rb -f ${{env.TMPFILE}}
          ruby annotate.rb -f ${{env.OUTFILE}} -o ./annotations.json
      - name: Annotate
        uses: yuzutech/annotations-action@v0.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          input: ./annotations.json
          title: 'Findings'
          ignore-missing-file: true
```
The annotations are displayed perfectly on the action page such as:
![ksnip_20210903-133500](https://user-images.githubusercontent.com/10864434/131992236-45106c2e-e3b9-4711-b850-e757e0b3b8f3.png)

But when clicking on the finding nothing gets displayed on the file anywhere I looked for (main PR page, commit page, files changed page). If a specific line has changed during the last commit it works, but on then next push if the line does not get changed  the failure message is not shown again.
First push with changed line:
![ksnip_20210903-134036](https://user-images.githubusercontent.com/10864434/131992999-5700f690-5ef0-40c0-af0d-72cf75f97364.png)

Second push with unchanged line (yet still finding in the job):
![ksnip_20210903-134325](https://user-images.githubusercontent.com/10864434/131993281-83ef474f-53d9-4de1-9f79-32a0fd391b6a.png)

Is there an option to maintain all findings even if not lines are changed on next commits such as this one according to my `annotations.json` file? Or even better to maintain all annotations on files changed?

Thank you!
