### ISSUE TITLE
SyntaxError: Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by nvjrepo** [yuzutech/annotations-action#63]
I got below error when running the package:
![image](https://github.com/yuzutech/annotations-action/assets/103881752/d0fa21ef-cdbe-4fb1-93fa-4e5dfd4665c8)

Below is the code i used
```
      - name: Lint dbt models
        id: sqlfluff_json
        #shell: bash -l {0}
        run: |
          git fetch origin main:main
          git diff main --name-only --diff-filter=d | egrep '^models/.*sql$$' | xargs -r sqlfluff lint --format github-annotation --annotation-level failure --nofail > annotations.json

      - name: Annotate
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'lint'
          input: './annotations.json'       
```
